#  TO  LOGIN TO DB ISE THIS COMMAND
# mysql -u root -p
# mysql -u test1 -p
---
- name: Installtion of MariaDB on centos-8
  hosts: app
  become: yes
  vars:
    mysql_root_password: "Password1"
    mysql_user : test1
    mysql_password: "12345"
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
        update_cache: yes
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: update mysql root password for all root accounts
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "{{ mysql_root_password }}"
        login_user: root
        login_password: "{{ mysql_root_password }}"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
    - name: Create a New Test DB called MyNewDB
      mysql_db: 
        name: MyNewDB 
        state: present 
        login_user: root 
        login_password: "{{ mysql_root_password }}"
    
    - name: Create MYSQL New user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_password }}"
        priv: "MyNewDB.*:ALL,GRANT"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"